[build]
  command = "npm ci --include=dev && npm run build"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[context.production.environment]
  PHP_VERSION = "8.3"

[dev]
  command = "npm run dev"
  port = 5173
